name: Test

permissions:
  contents: read

# this will be executed on every push on a branch (hence on every commit), but not when pushing a tag
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: fix test
        run: find ./ -name 'manifest.xml' -exec sed -i '' 's/edge530/fenix7/g' {} \; cat manifest.xml                   
    
      - uses: actions/checkout@v3
      - name: Test application
        id: run_tests
        uses: matco/action-connectiq-tester@v1
        with:
          device: fenix7
